Disable default partner_ids during calendar event creation
OCA/hr-holidays pull request #100
Opened 2023-11-29 10:53 UTC by moctarjallo

When you configure a public holiday in `hr.holidays.public.line` then a `calendar.event` calendar event linked to this public holiday (`meeting_id` field in `hr.holidays.public.line`) is automatically created with the `partner_ids` field filled in by the partner of the user who created the holiday.

This PR modifies so that when creating the calendar event `calendar.event` corresponding to the configured holiday `hr.holidays.public.line`, the `partner_ids` field is not filled in (leave empty).

2023-12-07 13:34 UTC, abhinavvaidya-tsd commented on hr_holidays_public/models/calendar_event.py
> +    def default_get(self, fields_list):
Please add @api.model decorator for better Odoo convention.

2023-12-07 13:52 UTC, abhinavvaidya-tsd approved these changes

2023-12-07 14:08 UTC, pedrobaeza requested changes

2023-12-07 14:08 UTC, pedrobaeza commented on hr_holidays_public/__manifest__.py
> +    "version": "16.0.1.2.0",
Please don't change manually the version, It's done by the bot on merge. This way, we avoid possible conflicts if there are several PRs for the same module done.

2023-12-07 14:08 UTC, pedrobaeza commented on hr_holidays_public/models/calendar_event.py
> +        defaults = super().default_get(fields_list)
Please don't do it this way, as this is affecting all the calendar events. Just pass `"partner_ids": False` in the dictionary creation instead.

2023-12-07 15:25 UTC, pedrobaeza reviewed
And please follow commit message guidelines:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

2023-12-07 15:25 UTC, pedrobaeza commented on hr_holidays_public/models/hr_holidays_public.py
> +            "partner_ids": False,
It seems this should be:

```suggestion
            "partner_ids": [],
```

2023-12-07 16:18 UTC, moctarjallo commented on hr_holidays_public/models/hr_holidays_public.py
> +            "partner_ids": False,
Right!

2023-12-07 16:26 UTC, pedrobaeza commented
The only thing left is the commit message. Please put for example:

```
[FIX] hr_holidays_public: Don't populate partner_ids on calendar event
```

2024-01-10 09:33 UTC, pedrobaeza approved these changes
/ocabot merge patch

Please fw-port it to v17

2024-01-10 09:35 UTC, merged