[18.0][MIG] hr_holidays_public: Migration to 18.0
OCA/hr-holidays pull request #147
Opened 2024-10-14 09:05 UTC by xaviedoanhduy

### Change on version 18.0

- `number_of_hours_display` fields has been removed in `https://github.com/odoo/odoo/pull/156117
`
### On the occasion

- I also removed some redundant code in tests (no need to call the denpends function)

### OCA - port

-  [17.0][FW] hr_holidays_public: port from 14.0: `https://github.com/OCA/hr-holidays/pull/144`

2024-10-16 09:33 UTC, mmequignon approved these changes

2024-10-16 09:39 UTC, pedrobaeza commented
/ocabot migration hr_holidays_public

2024-11-06 08:19 UTC, victoralmau requested changes
Code and functional review ok.

Could yo squash administrative commits?

2024-11-06 08:19 UTC, victoralmau commented on hr_holidays_public/models/hr_holidays_public.py
> +        partner = self._get_partner(partner_id)
IMO there is no need for the `_get_partner()` method, you can do it directly there `self.env["res.partner"].browse(partner_id)`

2024-11-06 08:19 UTC, victoralmau commented on hr_holidays_public/readme/CREDITS.md
> +The migration of this module from 17.0 to 18.0 was financially supported by Camptocamp.
This should not be changed.

2024-11-06 08:19 UTC, victoralmau commented on hr_holidays_public/views/hr_holidays_public_view.xml
> +                            readonly="variable_date == False"
```suggestion
                            readonly="not variable_date"
```

2024-11-06 09:46 UTC, xaviedoanhduy commented
hi @victoralmau, thanks for the suggestions

2024-11-06 10:54 UTC, victoralmau approved these changes

2024-11-06 12:29 UTC, pedrobaeza commented
We talk here about splitting the generic feature into a new module, and then provide an extension for HR:

https://github.com/OCA/hr-holidays/pull/110#issuecomment-2096096367

And what about the feature that Odoo has about the same concept?

cc @grindtildeath

2024-12-19 16:11 UTC, victoralmau commented
Please cherry-pick https://github.com/OCA/hr-holidays/pull/156 + https://github.com/OCA/hr-holidays/pull/157 to commit history.

My colleague's comment is still pending https://github.com/OCA/hr-holidays/pull/147#issuecomment-2459625077.

2024-12-20 17:52 UTC, grindtildeath commented
@pedrobaeza I wish I had more time to dive into this topic because the model exists since a few versions, but AFAICT standard public holidays still don't have the same flexibility as we have in the OCA module.

I guess a first step to converge both modules would be to have "rules" allowing creation of resource calendar leaves from the OCA holidays public.

Still, IMO would be nice to split the module to remove dependency on HR, and provide extension module for HR.

2024-12-20 18:53 UTC, pedrobaeza commented
Yes, we have talked today in my team about the Odoo core feature and it seems less complete than current one, and switching doesn't worth.

2024-12-26 11:57 UTC, xaviedoanhduy commented
hi i did some work:
- created PR for the extraction of the "public holiday" model to a new non-hr module, so that it could be used in other contexts: [[18.0][ADD] calendar_public_holiday](https://github.com/OCA/calendar/pull/142)
- prepared a new alternative PR for migration+refactoring of hr_holidays_public to depend on that new module [[18.0][MIG] hr_holidays_public: Migration to 18.0](https://github.com/OCA/hr-holidays/pull/159) 
let me know guys if this matches with your expectations

2025-01-08 15:50 UTC, victoralmau commented
Now that `calendar_public_holiday` already exists (https://github.com/OCA/calendar/pull/142), I believe that this PR should be modified to depend on `calendar_public_holiday` and only add the corresponding holidays. 
It would also be interesting migration scripts to convert the data: `calendar.event.type` and `hr.holidays.public` records to `calendar.public.holiday` (and lines).

2025-01-10 03:05 UTC, xaviedoanhduy commented
> Now that `calendar_public_holiday` already exists ([OCA/calendar#142](https://github.com/OCA/calendar/pull/142)), I believe that this PR should be modified to depend on `calendar_public_holiday` and only add the corresponding holidays. It would also be interesting migration scripts to convert the data: `calendar.event.type` and `hr.holidays.public` records to `calendar.public.holiday` (and lines).

hi @victoralmau, I've created a [alternative PR](https://github.com/OCA/hr-holidays/pull/159) to apply the new module dependency, but before I start working on the suggestion to write data migration scripts, I'm still not quite clear why `calendar.event.type` is there, or if you mean it should be `calendar.event` in the following code: https://github.com/OCA/hr-holidays/blob/e5d910b3eab4f83203602574e34ee2a91f0292a8/hr_holidays_public/models/hr_holidays_public.py#L146

2025-02-05 11:03 UTC, victoralmau commented
Can you modify this migration and add as a dependency `calendar_public_holiday` https://github.com/OCA/calendar/pull/142?

2025-02-05 11:34 UTC, xaviedoanhduy commented
> Can you modify this migration and add as a dependency `calendar_public_holiday` [OCA/calendar#142](https://github.com/OCA/calendar/pull/142)?

hi @victoralmau, i have created another PR to replace this PR in: https://github.com/OCA/hr-holidays/pull/159

2025-02-20 14:49 UTC, victoralmau commented
It seems that this PR can be closed in favor of https://github.com/OCA/hr-holidays/pull/159.

2025-02-21 02:36 UTC, closed without merging