[ADD] hr_holidays_leave_self_approve
OCA/hr-holidays pull request #70
Opened 2023-04-11 11:55 UTC by florentx

2023-05-05 18:27 UTC, rafaelbn commented
I think an better explanation should be in README as this can be done in Odoo Community without any module by:

- Setting approval to "no validation" or (better)
- Just setting "By Employee's Approver" and changing the domain of the field in the employee to it self.

Just curious, I would not use this module even when I allow my employees self-allow approvals 😄 

Not blocking anything! Regards

2023-09-04 07:00 UTC, florentx commented
> I think an better explanation should be in README as this can be done in Odoo Community without any module by:
> 
>     * Setting approval to "no validation" or (better)
> 
>     * Just setting "By Employee's Approver" and changing the domain of the field in the employee to it self.
> 

This add-on is useful for our use case because:

1. They want a validation, even if it is a self validation
2. Changing the domain of the field to the employee itself does not work because of this check in standard (Odoo 15)
```
# File "addons/hr_holidays/models/hr_leave.py"

                    if holiday.employee_id == current_employee:
                        raise UserError(_('Only a Time Off Manager can approve/refuse its own requests.'))
```

2023-09-04 07:26 UTC, simahawk requested changes

2023-09-04 07:26 UTC, simahawk commented on hr_holidays_leave_self_approve/__manifest__.py
> +    "author": "Camptocamp SA, Odoo Community Association (OCA)",
```suggestion
    "author": "Camptocamp, Odoo Community Association (OCA)",
```

2023-09-04 07:26 UTC, simahawk commented on hr_holidays_leave_self_approve/tests/test_hr_holidays_leave_self_approve.py
> +    def setUp(self):
pls use setUpClass and disable tracking

2023-09-04 07:26 UTC, simahawk commented on hr_holidays_leave_self_approve/__manifest__.py
> +    "summary": "Allow employee to approve his own leaves",
```suggestion
    "summary": "Allow employees to approve their own leaves when allowed",
```

2023-09-04 08:12 UTC, simahawk approved these changes

2024-01-30 10:46 UTC, gurneyalex approved these changes

2024-01-30 10:46 UTC, gurneyalex commented
/ocabot merge nobump

2024-05-02 16:01 UTC, dreispt commented
/ocabot merge nobump

2024-05-02 16:14 UTC, merged